import React, { useState, useRef, useEffect } from 'react';
import { MessageSquare, Send, X, Bot, Sparkles } from 'lucide-react';

interface ChatbotProps {
  setCurrentTab: (tab: string) => void;
}

interface Message {
  id: string;
  sender: 'user' | 'ai';
  text: string;
  timestamp: Date;
}

export const Chatbot: React.FC<ChatbotProps> = ({ setCurrentTab }) => {
  const [isOpen, setIsOpen] = useState(false);
  const [messages, setMessages] = useState<Message[]>([
    {
      id: 'welcome',
      sender: 'ai',
      text: "Hello! I am **PulseAI**, your onboarding copilot.\n\nI can help you navigate FleetPulse and explain what the app does. Try selecting one of the suggestions below or type a query like *'show me the live map'*!",
      timestamp: new Date(),
    },
  ]);
  const [input, setInput] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  // Auto-scroll to bottom of chat
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, isTyping]);

  const suggestions = [
    { label: 'Explore Live Map', query: 'Show me the Live Map' },
    { label: 'Optimize Routes', query: 'Open AI Insights' },
    { label: '⚠️ Check Alerts', query: 'Are there any critical alerts?' },
    { label: 'View Analytics', query: 'Show me the analytics charts' },
  ];

  const handleSend = (text: string) => {
    if (!text.trim()) return;

    const userMessage: Message = {
      id: Math.random().toString(36).substring(2, 9),
      sender: 'user',
      text: text,
      timestamp: new Date(),
    };

    setMessages((prev) => [...prev, userMessage]);
    setInput('');
    setIsTyping(true);

    // Simulate AI response delay
    setTimeout(() => {
      const response = processQuery(text);
      
      const aiMessage: Message = {
        id: Math.random().toString(36).substring(2, 9),
        sender: 'ai',
        text: response.message,
        timestamp: new Date(),
      };

      setMessages((prev) => [...prev, aiMessage]);
      setIsTyping(false);

      // Perform navigation if matched
      if (response.tab) {
        setCurrentTab(response.tab);
      }
    }, 850);
  };

  const processQuery = (text: string): { tab: string | null; message: string } => {
    const query = text.toLowerCase().trim();

    if (query.includes('map') || query.includes('live') || query.includes('gps') || query.includes('location') || query.includes('where is')) {
      return {
        tab: 'map',
        message: "Switching you to the **Live Map** page. \n\nHere you can see the real-time location of all operational vehicles. Each marker shows live speed and fuel levels, along with historical coordinate trails."
      };
    }
    if (query.includes('insight') || query.includes('predict') || query.includes('recommend') || query.includes('optimize') || query.includes('route')) {
      return {
        tab: 'insights',
        message: "Opening **AI Insights** dashboard. \n\nThis page highlights predictive delays generated by our forecast models (e.g. ETA adjustments based on weather/traffic anomalies) and lists operational recommendations to avoid penalties."
      };
    }
    if (query.includes('alert') || query.includes('warn') || query.includes('critical') || query.includes('issue')) {
      return {
        tab: 'alerts',
        message: "⚠️ Navigating to the **Alerts** center. \n\nThis view displays system violations logged in real-time (Speeding violations, Low fuel triggers, and Offline timeouts). Operators can inspect detailed logs and resolve active alerts."
      };
    }
    if (query.includes('fleet') || query.includes('truck') || query.includes('driver') || query.includes('vehicle')) {
      return {
        tab: 'fleet',
        message: "Taking you to the **Fleet Status** dashboard. \n\nThis tab displays a comprehensive directory of your vehicles, their telemetry logs, fuel metrics, driver identities, and status states (Moving, Idle, Offline)."
      };
    }
    if (query.includes('shipment') || query.includes('order') || query.includes('delivery') || query.includes('eta') || query.includes('progress')) {
      return {
        tab: 'shipments',
        message: "Redirecting to **Shipments**. \n\nThis section displays all active dispatches, showing shipment numbers, current progress percentages, origin/destination coordinates, and live estimated transit times."
      };
    }
    if (query.includes('analytic') || query.includes('chart') || query.includes('graph') || query.includes('metric') || query.includes('efficiency')) {
      return {
        tab: 'analytics',
        message: "Navigating to **Analytics**. \n\nHere we render rich statistical charts of fuel usage trends, speeding behavior ratios, and historical operational metrics of the entire logistics fleet."
      };
    }
    if (query.includes('report') || query.includes('log') || query.includes('csv') || query.includes('spreadsheet')) {
      return {
        tab: 'reports',
        message: "Opening the **Reports** section. \n\nOperators can run queries against telemetry data, aggregate distance metrics, and download official PDF reports of fleet activity."
      };
    }
    if (query.includes('setting') || query.includes('profile') || query.includes('password') || query.includes('theme')) {
      return {
        tab: 'settings',
        message: "Opening **Settings**. \n\nFrom here you can edit developer configurations, set safety thresholds (e.g., maximum speed, warning fuel limits), and customize user profiles."
      };
    }
    if (query.includes('dashboard') || query.includes('home') || query.includes('overview')) {
      return {
        tab: 'dashboard',
        message: "Returning to the main **Dashboard**.\n\nThis page displays critical KPIs (active trucks, on-time percentage, fuel stats, daily distance) along with a quick-glance active map and recent alert logs."
      };
    }
    if (query.includes('what is') || query.includes('app') || query.includes('do') || query.includes('fleetpulse') || query.includes('about')) {
      return {
        tab: null,
        message: "**FleetPulse** is a real-time cyber-logistics dashboard. \n\nIt aggregates telemetry logs from simulated cargo vehicles, evaluates status rules (Low Fuel, Speeding, Offline), registers system-wide alerts, and generates AI-driven route optimization insights."
      };
    }

    return {
      tab: null,
      message: "I didn't quite catch that. Here is what I can help you do:\n\n- Write **'show map'** to track vehicles in real-time.\n- Write **'open insights'** to find AI route suggestions.\n- Write **'view alerts'** to check critical warnings.\n- Write **'fleet status'** or **'shipments'** to list resources.\n- Write **'what is this app?'** to learn more."
    };
  };

  // Convert double-asterisk Markdown bold into React nodes
  const renderMessageText = (text: string) => {
    const parts = text.split(/(\*\*[^*]+\*\*)/g);
    return parts.map((part, index) => {
      if (part.startsWith('**') && part.endsWith('**')) {
        return <strong key={index} className="text-fp-accent-light font-semibold">{part.slice(2, -2)}</strong>;
      }
      return part;
    });
  };

  return (
    <>
      {/* Floating Action Trigger Button */}
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="fixed bottom-6 right-6 z-[9990] w-12 h-12 rounded-full bg-fp-accent text-white flex items-center justify-center shadow-lg hover:bg-fp-accent-light transition-all duration-300 group active:scale-95 animate-bounce-slow"
        title="Open PulseAI Guide"
      >
        {isOpen ? (
          <X className="w-5 h-5" />
        ) : (
          <div className="relative w-full h-full flex items-center justify-center">
            <span className="absolute inset-0 rounded-full bg-fp-accent/30 animate-ping group-hover:animate-none"></span>
            <MessageSquare className="w-5 h-5" />
          </div>
        )}
      </button>

      {/* Chat Card Panel */}
      {isOpen && (
        <div className="fixed bottom-22 right-6 z-[9990] w-[350px] max-w-[calc(100vw-2rem)] h-[460px] bg-fp-sidebar border border-fp-border rounded-xl shadow-card flex flex-col overflow-hidden backdrop-blur-md">
          {/* Header Bar */}
          <div className="px-4 py-3 bg-fp-card border-b border-fp-border flex justify-between items-center select-none">
            <div className="flex items-center gap-2">
              <div className="w-8 h-8 rounded-lg bg-fp-accent/15 border border-fp-accent/35 flex items-center justify-center">
                <Bot className="w-4 h-4 text-fp-accent-light" />
              </div>
              <div>
                <h3 className="text-xs font-semibold text-stone-200 flex items-center gap-1.5">
                  PulseAI Guide
                  <Sparkles className="w-3 h-3 text-fp-accent-light" />
                </h3>
                <span className="text-[9px] text-fp-success font-medium flex items-center gap-1">
                  <span className="w-1.5 h-1.5 rounded-full bg-fp-success animate-pulse"></span>
                  Online Assistant
                </span>
              </div>
            </div>
            
            <button
              onClick={() => setIsOpen(false)}
              className="text-stone-500 hover:text-stone-300 p-1 rounded hover:bg-white/[0.03] transition-colors"
              title="Close Guide"
            >
              <X className="w-4 h-4" />
            </button>
          </div>

          {/* Chat Messages Log */}
          <div className="flex-1 overflow-y-auto p-4 space-y-4 scroll-smooth">
            {messages.map((msg) => (
              <div
                key={msg.id}
                className={`flex gap-2 max-w-[85%] ${
                  msg.sender === 'user' ? 'ml-auto flex-row-reverse' : ''
                }`}
              >
                {msg.sender === 'ai' && (
                  <div className="w-6 h-6 rounded-full bg-fp-surface border border-fp-border flex items-center justify-center text-[10px] shrink-0 font-bold select-none text-fp-accent-light">
                    AI
                  </div>
                )}
                
                <div className={`p-3 rounded-lg text-xs leading-relaxed ${
                  msg.sender === 'user' 
                    ? 'bg-fp-accent/15 border border-fp-accent/30 text-stone-200' 
                    : 'bg-fp-card border border-fp-border text-stone-300'
                }`}>
                  <p className="whitespace-pre-line text-left">
                    {renderMessageText(msg.text)}
                  </p>
                  <span className="text-[8px] text-stone-600 font-medium block mt-1 text-right select-none">
                    {msg.timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                  </span>
                </div>
              </div>
            ))}

            {/* Bouncing Typing Dots */}
            {isTyping && (
              <div className="flex gap-2 max-w-[85%]">
                <div className="w-6 h-6 rounded-full bg-fp-surface border border-fp-border flex items-center justify-center text-[10px] shrink-0 font-bold select-none text-fp-accent-light">
                  AI
                </div>
                <div className="p-3 bg-fp-card border border-fp-border rounded-lg flex items-center gap-1 px-4">
                  <div className="w-1.5 h-1.5 rounded-full bg-stone-500 animate-bounce delay-100"></div>
                  <div className="w-1.5 h-1.5 rounded-full bg-stone-500 animate-bounce delay-200"></div>
                  <div className="w-1.5 h-1.5 rounded-full bg-stone-500 animate-bounce delay-300"></div>
                </div>
              </div>
            )}
            
            <div ref={messagesEndRef} />
          </div>

          {/* Prompt Suggestions */}
          <div className="px-4 py-2 bg-fp-card/40 border-t border-fp-border/40 select-none">
            <p className="text-[9px] text-stone-600 font-bold uppercase tracking-wider mb-1.5">
              Quick Suggestions
            </p>
            <div className="flex gap-1.5 overflow-x-auto pb-1 scrollbar-thin">
              {suggestions.map((sug, idx) => (
                <button
                  key={idx}
                  type="button"
                  onClick={() => handleSend(sug.query)}
                  className="px-2 py-1 bg-fp-surface hover:bg-fp-accent/10 border border-fp-border hover:border-fp-accent/35 text-[10px] text-stone-400 hover:text-fp-accent-light rounded-md whitespace-nowrap transition-all duration-150 active:scale-95 cursor-pointer"
                >
                  {sug.label}
                </button>
              ))}
            </div>
          </div>

          {/* Typing Form Input */}
          <form
            onSubmit={(e) => {
              e.preventDefault();
              handleSend(input);
            }}
            className="p-3 bg-fp-card border-t border-fp-border flex gap-2"
          >
            <input
              type="text"
              value={input}
              onChange={(e) => setInput(e.target.value)}
              placeholder="Ask about app features..."
              className="flex-1 bg-fp-surface border border-fp-border rounded-lg px-3 py-2 text-xs text-stone-200 placeholder-stone-600 focus:outline-none focus:border-fp-accent/50 focus:ring-1 focus:ring-fp-accent/20 transition-all"
            />
            <button
              type="submit"
              disabled={!input.trim()}
              className="w-8 h-8 rounded-lg bg-fp-accent hover:bg-fp-accent-light text-white flex items-center justify-center shrink-0 disabled:opacity-40 disabled:hover:bg-fp-accent transition-all duration-150 active:scale-95"
              title="Send Message"
            >
              <Send className="w-3.5 h-3.5" />
            </button>
          </form>
        </div>
      )}
    </>
  );
};
